config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'programming_language#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/search_programming_language', to: 'programming_language#search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/programming_language_controller.rb
# frozen_string_literal: true

# Controller for managing programming languages
class ProgrammingLanguageController < ApplicationController
  def index
    @programming_language = DATA
  end

  def search
    search_results = FilterProgrammingLanguageService.new(params[:query]&.downcase).call

    render turbo_stream: turbo_stream.replace('programming_language',
                                              partial: 'programming_language/table',
                                              locals: { programming_language: search_results })
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/programming_language_helper.rb
# frozen_string_literal: true

module ProgrammingLanguageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchWithoutDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programming_language/_table.html.erb
<%= turbo_frame_tag "programming_language" do %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Designed by</th>
      </tr>
    </thead>
    <tbody>
      <% programming_language.each do |programming_language| %>
        <tr>
          <td><%= programming_language[:Name] %></td>
          <td><%= programming_language[:Type] %></td>
          <td><%= programming_language[:"Designed by"] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/programming_language/index.html.erb
<div class="container">

  <%= form_with(url: search_programming_language_path, method: :get, data: { controller: "search-form", turbo_frame: "programming_language" }) do |form| %>
    <div class="input-group my-3">
      <%= form.text_field :query, class: "form-control", data: {action: "input->search-form#search"}, placeholder: "Search" %>
      <button class="btn btn-success" type="submit">Go</button>
    </div>
  <% end %>

  <h1 class="my-3">List of Programming Languages</h1>

  <%= turbo_frame_tag "programming_language" do %>
    <%= render partial: "programming_language/table", locals: { programming_language: @programming_language } %>
  <% end %>
</div>